### PR TITLE
Commenting and pygraphviz integration

### PR DESCRIPTION
**Pull request by remi-pr**
Hello,

Inspired by your very nice code / idea I thought I should try it out and got somehow carried away. I clearly had a lot of fun.

One mistake I should confess from the start is that I let PyCharm reformat some of the code (PEP8 compliance...) so that the diffs are actually hard to read. I am very sorry for that and I am willing to put it all back to the original format if you think this is necessary. (I did not think from the start I would write a pull request...)

I then added a lot of **comments / docstrings** where they actually helped me understand your code (and because you mentioned that in your todo list) That would mainly be in the `animation.py`, `render.py` and `dfv.py` files
##### The changes to your code are very minimal:
- I made `Animation.steps` and `Animation.graphs` properties instead of methods
- I added an `edges_nodes` property to `Animation` to get a list of all edges and nodes across all steps by using some code you wrote in the `Animation.graphs` method
##### Then I added some code:
- A `Animation.py_graphs` method that basically works like `Animation.graphs` but returns Pygraphviz objects
- Added a `_py_render` in `render.py` to be able to output Pygraphviz object the same way as you did before. It is integrated in the `render` function, and the correct renderer is chosen depending on the type of graphs that are passed as arguments. 

I hope you will find some of the changes interesting. Anyway, I had some fun going through all of your code, that I found very interesting and the idea is definitely a nice one. I am available in case something is unclear / wrong / should be deleted from this universe.

### CODE REVIEW

**Comment by mapio** [comment]
Thank you for your contribution! I'm presently quite busy, but I'll go through the edits as soon as possible to let you know. 

What can I say, at least initially, is that I will prefer to keep my code formatting. I know it's not PEP8, but I'm using it in all my other projects (since years), so I am not really willing to abdicate now :)  You would make my task easier if you can modify your pull request to at least recover my original formatting.

Moreover, I'd like to integrate with PyGraphviz, but without implying a strict dependency (as it is in your fork, that presently does not pass the tests due to pygraphviz missing). Even in this case, I'd like you to isolate the code depending on such package in a separate module (as I've done for Jupyter).

If you can modify your pull request in this way, it will be faster for me to analyse it to proceed in case with the merge.

Thank you for your time and effort!

**Comment by remi-pr** [comment]
Again, sorry for the change in formatting, that was a mistake, it is now back to your original format. I also isolated the PyGraphviz code in a separate file (in a very crude way). Now the tests are passing.

Cheers.

**Comment by mapio** [comment]
No need to say sorry! Thank you, indeed. As soon as I'll have a bit of time I'll read you code and integrate/merge it!

**Comment by mapio** [comment]
Please check the above comments in the code where I've pinned them. 

I'll be about a deep rewrite of highlighting according to mapio/GraphvizAnim#8.

What I suggest is that you give me a bit of time to write the code that I've in mind and then evaluate if you still want to fix the pull request according to my comments here. :)

I'm sorry for being so picky and altering the codebase during a pull request, but it's still very very alpha and I am still in the process of designing parts of it.

**Comment by remi-pr** [comment]
I am going through your comments. No worries about being picky. I 
basically spent a few hours late at night on it I just thought I would 
submit something because I liked your idea.

**Comment by mapio** [comment]
I've seen no activity on this since a long time. If I'm wrong I'll consider reopening it (but first conflicts with present version should be resolved).

**Pull request closed without merging**
