### PR TITLE
add optional argument for custom highlight color

### LINKED ISSUE #8: Make highlighting use an optional color (not just red)
Modify the way highlighting is handled: instead of using a set (to keep track of highlighted nodes/edges), use a dict to map highlighted nodes/edges to their color (and add an optional parameter to the highlight methods).

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #8.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@mapio It would be great if you could review this when you get a chance. Please also consider to make a new release afterwards in order to make the recent changes and fixes available to users using the latest release.

**Comment by dirk-thomas** [comment]
@mapio Thanks for merging this. Would you like to wait with a new release until other changes or would you consider releasing a new version with the current state?

**Comment by mapio** [comment]
Isn't https://github.com/mapio/GraphvizAnim/releases/tag/0.3-alpha what is needed? Help me if I'm wrong @dirk-thomas

**Comment by dirk-thomas** [comment]
@mapio Sorry, I missed the new tag. I was only looking for a commit on master to level the version which is still [0.2-alpha](https://github.com/mapio/GraphvizAnim/blob/de3cef49c73ab902c2429130e05025df04a5700f/setup.py#L9).

**Comment by dirk-thomas** [comment]
It would also be nice to upload the new version to PyPI which still has 0.2-alpha: https://pypi.python.org/pypi/GraphvizAnim/

**Comment by mapio** [comment]
As soon as I’ll find my credentials :-( and remember how to do the upload…

**Comment by dirk-thomas** [comment]
@mapio Any news on this?

**Comment by mapio** [comment]
It should be okay, now [PyPI history](https://pypi.org/project/GraphvizAnim/#history) for the project reports 0.3.1-alpha (released Mar 17, 2018).

**Comment by mapio** [comment]
Since I had a few more fixes (and I wanted the new PyPI to have a markdown readme), I've uploaded a 1.0.2 version that is online now.

**Comment by dirk-thomas** [comment]
Thanks, I guess I just missed it since the commits didn't show any activity.

**Pull request merged**
